### ISSUE TITLE
Hi sir

### ISSUE THREAD

**Issue by Turing551** [BirukTes/AWH-HATMS#16]
I need a project to be dome same as the hospital management system. please tell me your mail id . I will sendd the documentation

**Comment by Turing551** [comment]
Otherwise Please help me how to work on this. Means the required installation etc. Please help me

**Comment by BirukTes** [comment]
@Turing551 hey, sorry for the late reply.  

Let know me, if you still need help, so we can do something about it.

To install this:

1) You can follow this, https://www.youtube.com/watch?v=pPy0GQJLZUM&t=67s  to get started.
   1) Make sure to install `Postgres 10`, and setup accordingly
   2) Make sure to install `Ruby 2.41, Rails 5.1.5`
2) Run the command, `bundle` to install all gems
3) Run the Rails Server, and access the localhost:3000 from a browser
